Tushare数据读取

In [15]:
import pandas as pd
import tushare as ts
pro = ts.pro_api("f5ca7a922f41929faa97832f0fbe87e6ba523cf3e1db472612d3f3a4")

In [ ]:
def get_all_stocks_and_indexes():
    """
    获取所有A股股票和沪深指数代码
    
    Returns:
        股票和指数代码列表
    """
    
    try:
        # 获取所有A股股票
        stock_df = pro.stock_basic(
            exchange='',
            list_status='L',
            fields='ts_code,symbol,name,list_date,market'
        )
        
        # # 过滤掉ST、*ST、退市股票
        # stock_df = stock_df[
        #     ~stock_df['name'].str.contains('ST') &
        #     ~stock_df['name'].str.contains('退') &
        #     (stock_df['list_date'] <= '20251231')
        # ]
        
        # 获取沪深指数
        index_df = pro.index_basic(
            market='SSE,SZSE',
            fields='ts_code,name,list_date'
        )
        
        # 选择主要指数
        main_indexes = [
            '000001.SH',  # 上证指数
            '000300.SH',  # 沪深300
            '000905.SH',  # 中证500
            '399001.SZ',  # 深证成指
            '399006.SZ',  # 创业板指
            '399005.SZ',  # 中小板指
            '000016.SH',  # 上证50
            '000852.SH',  # 中证1000
        ]
        # index_df = index_df[index_df['ts_code'].isin(main_indexes)]
        print(len(stock_df), len(index_df))
        # 合并代码
        all_codes = pd.concat([
            stock_df['ts_code'],
            index_df['ts_code']
        ], ignore_index=True).drop_duplicates().tolist()
        
        print(f"获取完成: 共{len(stock_df)}只股票, {len(index_df)}个指数, 总计{len(all_codes)}个代码")
        return all_codes
        
    except Exception as e:
        print(f"获取代码列表失败: {e}")
        raise

In [ ]:
all_codes = get_all_stocks_and_indexes()

In [ ]:
# 获取所有A股股票
stock_df = pro.stock_basic(
    exchange='',
    list_status='L',
    fields='ts_code,symbol,name,list_date,market'
)

In [ ]:
df = pro.index_basic(market='SSE')

In [ ]:
df

In [ ]:
stock_df

In [3]:

#获取浦发银行60000.SH的历史分钟数据
df1 = pro.stk_mins(ts_code='002759.SZ', freq='30min', start_date='2010-01-01 09:00:00', end_date='')

print(len(df1))

8000

In [5]:
# 2018-09-14 11:00:00
#2022-05-23 10:00:00
df2 = pro.stk_mins(ts_code='002759.SZ', freq='30min', start_date='2010-01-01 09:00:00', end_date='2022-05-23 10:00:00')

print(len(df2))

8000

In [7]:
# 2018-09-14 11:00:00
#2022-05-23 10:00:00
df3 = pro.stk_mins(ts_code='002759.SZ', freq='30min', start_date='2010-01-01 09:00:00', end_date='2018-09-14 11:00:00')

print(len(df3))

7267

In [ ]:
dfs = pd.DataFrame()
pd.concat([df, df2, df3]).drop

In [6]:
df2

,ts_code,trade_time,close,open,high,low,vol,amount
0,002759.SZ,2022-05-23 10:00:00,23.20,23.27,23.48,23.09,4277678.0,99564600.0
1,002759.SZ,2022-05-23 09:30:00,23.28,23.31,23.32,23.26,100400.0,2340122.0
2,002759.SZ,2022-05-20 15:00:00,23.31,23.25,23.35,23.13,2439200.0,56805252.0
3,002759.SZ,2022-05-20 14:30:00,23.25,23.08,23.32,23.02,1595900.0,37000864.0
4,002759.SZ,2022-05-20 14:00:00,23.09,23.03,23.16,22.98,779300.0,17988708.0
...,...,...,...,...,...,...,...,...
7995,002759.SZ,2018-09-14 14:30:00,8.07,8.07,8.08,8.05,98202.0,791856.1
7996,002759.SZ,2018-09-14 14:00:00,8.07,8.08,8.09,8.06,83800.0,676546.0
7997,002759.SZ,2018-09-14 13:30:00,8.07,8.05,8.08,8.04,43350.0,349671.5
7998,002759.SZ,2018-09-14 11:30:00,8.05,8.08,8.08,8.03,179200.0,1442948.0
7999,002759.SZ,2018-09-14 11:00:00,8.07,8.08,8.10,8.07,72700.0,587241.0

In [8]:
print(df3.head(1)['trade_time'])
df3.tail(1)['trade_time']

0    2018-09-14 11:00:00
Name: trade_time, dtype: object

7266    2015-05-28 09:30:00
Name: trade_time, dtype: object

In [ ]:
print(df.head(2))
print(df.tail(2))

In [9]:
dfs = pd.concat([df1, df2, df3]).drop_duplicates().sort_index()

In [13]:
len(dfs)
dfs.sort_values(by=['trade_time'], ascending=True)

,ts_code,trade_time,close,open,high,low,vol,amount
7266,002759.SZ,2015-05-28 09:30:00,12.02,12.02,12.02,12.02,0.0,0.0
7265,002759.SZ,2015-05-28 10:00:00,17.31,15.86,17.31,15.86,7200.0,123907.0
7264,002759.SZ,2015-05-28 10:30:00,17.31,17.31,17.31,17.31,1100.0,19041.0
7263,002759.SZ,2015-05-28 11:00:00,17.31,17.31,17.31,17.31,2000.0,34620.0
7262,002759.SZ,2015-05-28 11:30:00,17.31,17.31,17.31,17.31,500.0,8655.0
...,...,...,...,...,...,...,...,...
4,002759.SZ,2026-01-15 11:30:00,45.22,45.71,45.74,45.03,5050000.0,229144140.0
3,002759.SZ,2026-01-15 13:30:00,45.39,45.22,45.69,45.03,4432341.0,201054670.0
2,002759.SZ,2026-01-15 14:00:00,45.02,45.39,45.42,45.02,2798778.0,126383190.0
1,002759.SZ,2026-01-15 14:30:00,45.04,45.03,45.20,44.80,4713900.0,211983680.0
0,002759.SZ,2026-01-15 15:00:00,45.15,45.05,45.25,44.93,7309809.0,329649820.0

In [18]:
ts.set_token('f5ca7a922f41929faa97832f0fbe87e6ba523cf3e1db472612d3f3a4')

In [ ]:
day = ts.pro_bar(ts_code='002759.SZ', freq="30min", adj='qfq', start_date='20150528', end_date='20260111')

In [25]:
day2 = ts.pro_bar(ts_code='002759.SZ', freq="30min", adj='qfq', start_date='20150528', end_date='2022-05-17 10:00:00')

In [ ]:
day2

,ts_code,trade_time,close,open,high,low,vol,amount
0,002759.SZ,2022-05-17 10:00:00,22.03,21.61,22.14,21.50,2954700.0,64480120.0
1,002759.SZ,2022-05-17 09:30:00,21.61,21.63,21.63,21.61,20100.0,434720.0
2,002759.SZ,2022-05-16 15:00:00,21.71,21.76,21.82,21.71,1071012.0,23293486.0
3,002759.SZ,2022-05-16 14:30:00,21.76,21.85,21.87,21.66,545600.0,11863123.0
4,002759.SZ,2022-05-16 14:00:00,21.85,21.70,21.95,21.67,671600.0,14663325.0
...,...,...,...,...,...,...,...,...
7995,002759.SZ,2018-09-10 14:30:00,8.00,8.02,8.04,7.97,202400.0,1626054.0
7996,002759.SZ,2018-09-10 14:00:00,8.02,8.00,8.04,7.99,77500.0,623730.0
7997,002759.SZ,2018-09-10 13:30:00,8.01,8.05,8.05,7.97,230500.0,1857006.0
7998,002759.SZ,2018-09-10 11:30:00,8.05,8.08,8.08,8.05,40900.0,331257.0
7999,002759.SZ,2018-09-10 11:00:00,8.07,8.05,8.08,8.02,226100.0,1828894.0

: