## 回测结果查看

In [1]:
import pandas as pd
from chanlun.backtesting import backtest
from chanlun.config import get_data_path
from chanlun.strategy.my_strategy_dnbbc_202516 import StrategyDnbbc

c:\Users\Zhou\anaconda3\envs\chanlun\Lib\site-packages\pyfolio\pos.py:25: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(

Chanlun-Pro 缠论数据计算
https://gitee.com/wang-student/chanlun-pro
运行环境: Python: 3.11
授权信息: A_hia_hia_hia-VIP
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

In [2]:
save_bt_path = "D:/xuangu_log/backtrade/"

In [ ]:
save_bt_path

In [21]:
# 从保存的回测落地文件中加载数据
# save_file = str(get_data_path() / "backtest" / "a_w_mmd_v0_signal.pkl")
# save_path = 'D:/xuangu_log/a_strategy_Dnbbc_20250114/'
# save_file = "D:/xuangu_log/a_strategy_Dnbbc_20250107/a_strategy_Dnbbc_20250107.pkl"
save_file = "D:/xuangu_log/backtrade/backtrade_signal_to_trade_profit_loss_rate_False_5.pkl"
save_bt_path = "D:/xuangu_log/backtrade/" + save_file.split("/")[-2]
BT = backtest.BackTest()
BT.load(save_file)
# 显示回测配置与结果
BT.info()
BT.result()

2025-01-08 22:43:42
保存地址 : D:/xuangu_log/backtrade/backtrade_signal_to_trade_profit_loss_rate_False_5.pkl
回测模式 【trade】市场 【a】初始资金 【1000000】 手续费率 【0.0006】
策略 : <chanlun.strategy.my_strategy_dnbbc_202516.StrategyDnbbc object at 0x0000020F53C3F8D0>
基准代码 : SH.000001
回测代码 : ['SZ.002131', 'SH.600600', 'SH.601619', 'SH.600814', 'SZ.300430', 'SZ.300333', 'SZ.300265', 'SH.601117', 'SH.603378', 'SZ.301015', 'SH.603387', 'SH.600883', 'SH.601038', 'SH.688315', 'SZ.002236', 'SZ.300295', 'SH.603301', 'SH.603856', 'SZ.000972', 'SH.603988', 'SZ.300174', 'SZ.300213', 'SZ.301096', 'SH.601808', 'SH.603855', 'SH.600809', 'SZ.300355', 'SH.600016', 'SZ.002718', 'SH.600562', 'SZ.001696', 'SZ.300761', 'SZ.300044', 'SH.600801', 'SZ.300429', 'SZ.002887', 'SZ.002458', 'SZ.300733', 'SH.605377', 'SH.600178', 'SZ.000626', 'SZ.300326', 'SZ.300602', 'SZ.002280', 'SZ.300663', 'SH.605086', 'SZ.002906', 'SH.600531', 'SH.603300', 'SH.605186', 'SH.688029', 'SZ.002122', 'SZ.300809', 'SH.601991', 'SZ.003019', 'SZ.300331', 'SZ.300169', 'SZ.002939', 'SZ.002707', 'SZ.300750', 'SZ.000506', 'SZ.002562', 'SH.601500', 'SH.600839', 'SH.603711', 'SH.601375', 'SZ.002793', 'SZ.300757', 'SH.603683', 'SZ.300896', 'SZ.002576', 'SZ.300370', 'SZ.300473', 'SZ.002101', 'SH.600362', 'SZ.002256', 'SZ.300022', 'SZ.300345', 'SZ.002935', 'SZ.000726', 'SH.603006', 'SZ.300678', 'SH.600313', 'SZ.300328', 'SH.600052', 'SH.601139', 'SZ.002705', 'SH.688191', 'SZ.002556', 'SH.688082', 'SZ.000590', 'SZ.002073', 'SH.600280', 'SH.600568', 'SH.603297', 'SH.600685', 'SH.600331', 'SZ.002034', 'SH.603056', 'SZ.002264', 'SZ.002856', 'SZ.300275', 'SH.603689', 'SZ.300843', 'SZ.002152', 'SH.600855', 'SH.600889', 'SZ.300798', 'SZ.300007', 'SZ.002097', 'SZ.300833', 'SZ.002354', 'SZ.000813', 'SZ.002873', 'SH.600162', 'SH.603730', 'SZ.002229', 'SH.600182', 'SZ.300137', 'SZ.000729', 'SZ.002796', 'SZ.002988', 'SH.600641', 'SH.600536', 'SH.600590', 'SZ.000529', 'SH.601702', 'SZ.002641', 'SZ.300569', 'SH.600468', 'SH.600309', 'SH.600312', 'SZ.300845', 'SZ.000960', 'SZ.300335', 'SZ.002807', 'SH.603786', 'SH.603608', 'SH.603311', 'SZ.002010', 'SZ.002531', 'SZ.002674', 'SH.688228', 'SH.603787', 'SH.688065', 'SZ.000069', 'SZ.300280', 'SZ.300756', 'SZ.300825', 'SZ.300538', 'SH.600217', 'SH.600397', 'SH.605081', 'SZ.002159', 'SH.688229', 'SZ.002431', 'SZ.002502', 'SZ.002715', 'SZ.300113', 'SZ.002737', 'SZ.300218', 'SZ.300541', 'SH.600055', 'SH.688711', 'SZ.002081', 'SZ.300188', 'SH.601231', 'SZ.000509', 'SZ.002219', 'SZ.300672', 'SZ.000962', 'SZ.000027', 'SZ.000059', 'SH.600080', 'SZ.300991', 'SZ.300234', 'SZ.300570', 'SZ.002112', 'SH.600166', 'SZ.300172', 'SH.603041', 'SZ.000550', 'SH.600011', 'SH.601015', 'SZ.000708', 'SZ.002046', 'SZ.300749', 'SZ.300387', 'SH.605168', 'SH.600459', 'SH.600692', 'SZ.000049', 'SH.601669', 'SZ.002275', 'SZ.300670', 'SH.600239', 'SZ.002634', 'SH.688323', 'SH.603015', 'SZ.300892', 'SZ.000066', 'SH.688019', 'SH.688008', 'SH.603328', 'SH.603336', 'SZ.002620', 'SZ.300259', 'SH.601111', 'SZ.000407', 'SZ.300810', 'SZ.000878', 'SZ.300668', 'SZ.300778', 'SH.603757', 'SH.600987', 'SH.603626', 'SZ.002090', 'SH.688020', 'SZ.300207', 'SZ.000967', 'SZ.300324', 'SH.600116', 'SH.603351', 'SZ.300620', 'SZ.300221', 'SZ.000892', 'SZ.000971', 'SZ.300553', 'SZ.002160', 'SH.601318', 'SH.605337', 'SH.600578', 'SH.600105', 'SH.600916', 'SH.600996', 'SZ.002052', 'SH.603809', 'SH.600599', 'SZ.002017', 'SZ.002345', 'SZ.002831', 'SZ.300101', 'SH.600793', 'SH.603506', 'SZ.002291', 'SH.600115', 'SH.688113', 'SZ.002498', 'SZ.000963', 'SH.688388', 'SZ.002361', 'SH.600386', 'SH.600425', 'SZ.002623', 'SZ.002180', 'SH.600462', 'SH.600300', 'SH.603020', 'SZ.000333', 'SZ.300818', 'SZ.300736', 'SZ.002063', 'SZ.002862', 'SZ.000860', 'SH.605158', 'SZ.300025', 'SZ.300713', 'SZ.002016', 'SH.600787', 'SH.603685', 'SZ.002926', 'SZ.002187', 'SH.603017', 'SZ.300946', 'SH.600328', 'SH.601137', 'SZ.300245', 'SH.603600', 'SH.603983', 'SZ.002610', 'SZ.000035', 'SH.603927', 'SZ.300302', 'SZ.300690', 'SH.603303', 'SH.603355', 'SH.603105', 'SZ.000428', 'SH.600233', 'SZ.002338', 'SZ.002127', 'SZ.300139', 'SZ.300472', 'SZ.300579', 'SZ.002371', 'SZ.300514', 'SH.603025', 'SH.688466', 'SH.603103', 'SZ.002395', 'SZ.300507', 'SH.603222', 'SZ.300127', 'SH.600919', 'SH.603718', 'SH.605018', 'SZ.300351', 'SZ.300537', 'SZ.002682', 'SH.601598', 'SZ.300887', 'SZ.300254', 'SH.600137', 'SH.601975', 'SZ.002843', 'SZ.000503', 'SH.601789', 'SH.603707', 'SZ.002062', 'SZ.300399', 'SZ.002384', 'SZ.000859', 'SZ.002816', 'SH.603268', 'SH.688166', 'SH.688188', 'SH.600199', 'SH.601607', 'SZ.300170', 'SH.601336', 'SZ.300444', 'SZ.300448', 'SH.600221', 'SZ.300697', 'SZ.002884', 'SZ.300190', 'SZ.300304', 'SH.600626', 'SZ.300943', 'SH.603067', 'SH.688510', 'SZ.002178', 'SH.603599', 'SZ.002255', 'SZ.000679', 'SZ.002427', 'SZ.002196', 'SH.688186', 'SH.605128', 'SZ.000608', 'SH.603396', 'SH.600131', 'SH.600741', 'SZ.002368', 'SH.600252', 'SH.601326', 'SZ.002721', 'SH.603158', 'SZ.300383', 'SH.688017', 'SH.688360', 'SH.688106', 'SZ.300424', 'SZ.300185', 'SZ.300493', 'SZ.300661', 'SH.603726', 'SZ.300005', 'SZ.300290', 'SZ.002492', 'SZ.002274', 'SZ.002984', 'SZ.000977', 'SZ.002991', 'SZ.002234', 'SH.688160', 'SH.603893', 'SH.601456', 'SH.601208', 'SZ.000700', 'SH.601608', 'SH.600503', 'SH.600579', 'SH.603808', 'SZ.300557', 'SZ.001914', 'SH.600638', 'SH.603180', 'SH.600587', 'SH.603379', 'SH.603833', 'SZ.002300', 'SH.600871', 'SZ.300864', 'SH.600066', 'SH.600551', 'SH.601577', 'SZ.002027', 'SZ.002123', 'SZ.300572', 'SZ.002039', 'SH.603919', 'SZ.002918', 'SH.605068', 'SZ.002806', 'SZ.300531', 'SZ.000533', 'SH.601717', 'SZ.002003', 'SZ.002506', 'SZ.002508', 'SZ.301179', 'SZ.002273', 'SZ.300691', 'SH.600827', 'SZ.300050', 'SZ.300411', 'SZ.300425', 'SH.600135', 'SH.601212', 'SH.603909', 'SZ.000065', 'SZ.300314', 'SZ.301052', 'SZ.002990', 'SH.600262', 'SZ.300841', 'SZ.002446', 'SH.603713', 'SZ.300196', 'SZ.002608', 'SZ.002702', 'SH.603212', 'SZ.000596', 'SZ.002647', 'SH.603992', 'SH.603199', 'SZ.002578', 'SH.600477', 'SZ.300258', 'SH.600382', 'SH.603330', 'SH.688356', 'SZ.002629', 'SZ.000661', 'SZ.300012', 'SH.600375', 'SZ.002045', 'SZ.300470', 'SH.603183', 'SZ.300072', 'SZ.300638', 'SZ.002085', 'SZ.002743', 'SZ.002664', 'SH.603037', 'SH.600782', 'SZ.300031', 'SH.603090', 'SH.603527', 'SZ.300680', 'SH.600546', 'SZ.002426', 'SZ.002908', 'SH.600584', 'SZ.300644', 'SZ.301008', 'SZ.300086', 'SH.603823', 'SZ.002752', 'SH.601777', 'SH.603536', 'SZ.001872', 'SZ.002115', 'SZ.002650', 'SH.603266', 'SH.600480', 'SH.603081', 'SZ.002182', 'SH.603886', 'SZ.300571', 'SZ.002938', 'SH.601088', 'SZ.002736', 'SZ.002920', 'SZ.000839', 'SZ.002546', 'SZ.002114', 'SZ.002448', 'SZ.002929', 'SZ.300830', 'SZ.300738', 'SH.600650', 'SH.600435', 'SZ.300298', 'SZ.000830', 'SH.600097', 'SZ.300018', 'SZ.002080', 'SH.688128', 'SH.688655', 'SH.688003', 'SZ.002899', 'SZ.002369', 'SZ.300446', 'SH.603677', 'SZ.002973', 'SZ.000055', 'SZ.300056', 'SZ.300323', 'SZ.002028', 'SH.603885', 'SZ.002452', 'SZ.000409', 'SZ.002007', 'SZ.300341', 'SH.603596', 'SH.603903', 'SZ.300555', 'SZ.002572', 'SH.688676', 'SH.601727', 'SH.603305', 'SZ.000801', 'SZ.300242', 'SZ.000779', 'SZ.002970', 'SZ.002179', 'SZ.002132', 'SZ.300138', 'SZ.300194', 'SZ.000869', 'SZ.300492', 'SZ.300129', 'SH.600645', 'SH.603610', 'SH.603121', 'SZ.300848', 'SH.600676', 'SH.605008', 'SH.600875', 'SH.601155', 'SZ.000951', 'SZ.300173', 'SH.688513', 'SZ.002138', 'SH.603825', 'SZ.300567', 'SZ.002168', 'SZ.002083', 'SZ.300543', 'SZ.002449', 'SH.601928', 'SZ.300243', 'SH.600909', 'SZ.300010', 'SZ.300329', 'SH.603722', 'SH.605299', 'SZ.300568', 'SZ.000922', 'SH.600160', 'SZ.002479', 'SZ.002555', 'SZ.300305', 'SH.600863', 'SH.601228', 'SZ.300029', 'SZ.300915', 'SZ.002456', 'SZ.000565', 'SZ.300141', 'SZ.002462', 'SH.603859', 'SZ.002441', 'SH.600684', 'SZ.000826', 'SZ.300683', 'SZ.002981', 'SZ.000415', 'SZ.000659', 'SZ.000582', 'SH.603848', 'SZ.000928', 'SZ.300121', 'SH.688037', 'SH.603369', 'SZ.002930', 'SH.600213', 'SH.603488', 'SZ.300575', 'SH.603236', 'SH.601929', 'SH.600185', 'SZ.300722', 'SZ.003012', 'SZ.301050', 'SH.600101', 'SH.600035', 'SZ.002701', 'SZ.000559', 'SZ.300100', 'SZ.002397', 'SZ.002750', 'SH.688418', 'SZ.002290', 'SZ.300084', 'SH.603609', 'SH.603123', 'SH.603326', 'SH.603727', 'SH.601618', 'SZ.000938', 'SH.600082', 'SH.688663', 'SZ.300790', 'SH.603288', 'SZ.000933', 'SZ.002119', 'SZ.300052', 'SH.603239', 'SH.600523', 'SZ.000683', 'SZ.000915', 'SH.603515', 'SH.688230', 'SZ.000751', 'SZ.300434', 'SH.603085', 'SZ.300215', 'SZ.300777', 'SH.601000', 'SZ.300224', 'SH.603989', 'SH.603228', 'SH.603661', 'SZ.000513', 'SZ.002727', 'SZ.002105', 'SH.600195', 'SZ.300201', 'SH.603321', 'SZ.000887', 'SZ.300037', 'SH.688028', 'SZ.002483', 'SH.603898', 'SZ.000557', 'SZ.002142', 'SH.600288', 'SZ.300719', 'SZ.002032', 'SZ.002517', 'SZ.002233', 'SZ.300423', 'SH.600399', 'SH.603188', 'SZ.002047', 'SZ.002789', 'SZ.300970', 'SH.600206', 'SZ.002529', 'SZ.002311', 'SH.600152', 'SH.603517', 'SZ.300346', 'SZ.002599', 'SZ.300866', 'SZ.002883', 'SZ.300176', 'SZ.300611', 'SH.601633', 'SZ.002111', 'SZ.300165', 'SZ.300065', 'SZ.000636', 'SH.600592', 'SZ.300308', 'SZ.300872', 'SH.600038', 'SH.600073', 'SZ.000949', 'SH.601939', 'SZ.002253', 'SZ.300376', 'SH.603568', 'SH.605218', 'SZ.002413', 'SH.600285', 'SH.603818', 'SH.603323', 'SZ.002681', 'SZ.000753', 'SZ.002685', 'SH.600730', 'SZ.300223', 'SZ.301131', 'SZ.000523', 'SZ.000883', 'SH.603861', 'SH.603606', 'SZ.000966', 'SZ.300436', 'SZ.300348', 'SH.600545', 'SH.601512', 'SH.605116', 'SZ.300257', 'SH.600674', 'SZ.002475', 'SZ.300748', 'SZ.000796', 'SZ.002344', 'SZ.300536', 'SZ.000410', 'SZ.002648', 'SZ.300828', 'SZ.300706', 'SZ.000571', 'SH.600733', 'SH.600380', 'SZ.002325', 'SZ.002214', 'SZ.002351', 'SH.600029', 'SZ.002328', 'SZ.000429', 'SH.600764', 'SZ.300783', 'SZ.000701', 'SZ.000552', 'SZ.300596', 'SZ.002059', 'SH.601238', 'SH.600702', 'SH.600259', 'SH.603109', 'SZ.002471', 'SZ.002444', 'SZ.002637', 'SZ.00193', 'SZ.002443', 'SH.601901', 'SZ.300375', 'SH.600961', 'SZ.002078', 'SH.600619', 'SZ.002677', 'SH.603605', 'SZ.002817', 'SZ.002433', 'SH.603360', 'SZ.300222', 'SZ.000738', 'SZ.000006', 'SZ.002538', 'SH.600797', 'SH.603338', 'SH.688366', 'SH.688215', 'SZ.002223', 'SH.603110', 'SZ.000932', 'SZ.002520', 'SH.600335', 'SH.603009', 'SH.688321', 'SZ.300252', 'SZ.000561', 'SZ.300643', 'SH.603042', 'SZ.002207', 'SZ.002544', 'SH.600758', 'SH.600821', 'SZ.002387', 'SH.600505', 'SZ.300610', 'SH.688057', 'SZ.300002', 'SH.603259', 'SH.603773', 'SH.601021', 'SH.603088', 'SH.600559', 'SZ.003013', 'SZ.300203', 'SH.601229', 'SZ.000930', 'SH.600017', 'SH.600979', 'SZ.000692', 'SH.603698', 'SZ.002989', 'SH.603528', 'SZ.300692', 'SH.600998', 'SH.600522', 'SZ.002405', 'SH.688007', 'SH.688096', 'SZ.300595', 'SH.600841', 'SZ.300857', 'SZ.002109', 'SZ.002947', 'SH.600877', 'SH.600682', 'SH.601688', 'SZ.002277', 'SZ.300098', 'SH.603068', 'SZ.000060', 'SZ.002742', 'SH.600558', 'SH.600203', 'SH.600287', 'SZ.002527', 'SH.600509', 'SZ.002019', 'SH.601778', 'SH.688300', 'SZ.002982', 'SH.601108', 'SZ.002978', 'SZ.002782', 'SH.603580', 'SZ.300666', 'SZ.002065', 'SZ.002749', 'SH.603658', 'SZ.300566', 'SH.600130', 'SH.601555', 'SH.603987', 'SH.688488', 'SZ.300577', 'SH.600019', 'SZ.300183', 'SZ.300589', 'SZ.300070', 'SZ.002728', 'SZ.003026', 'SH.603721', 'SZ.002524', 'SH.603160', 'SZ.000036', 'SZ.300047', 'SH.601890', 'SH.603920', 'SH.603018', 'SH.603507', 'SH.601127', 'SZ.300590', 'SZ.002870', 'SZ.300613', 'SH.600150', 'SZ.300580', 'SH.600316', 'SZ.002837', 'SH.600298', 'SH.600836', 'SZ.002053', 'SZ.002042', 'SZ.002739', 'SZ.002353', 'SZ.300599', 'SZ.301076', 'SZ.000629', 'SZ.000983', 'SZ.300062', 'SZ.000045']
周期 : ['d', '30m']
起始时间 : 2019-01-01 00:00:00 结束时间 : 2024-12-31 15:00:00
缠论配置 : {'config_use_type': 'common', 'kline_type': 'kline_default', 'kline_qk': 'none', 'fx_qj': 'fx_qj_ck', 'fx_bh': 'fx_bh_no', 'bi_type': 'bi_type_old', 'bi_bzh': 'bi_bzh_yes', 'bi_qj': 'bi_qj_ck', 'bi_fx_cgd': 'bi_fx_cgd_no', 'xd_qj': 'xd_qj_ck', 'zsd_qj': 'zsd_qj_ck', 'zs_bi_type': ['zs_type_fl'], 'zs_xd_type': ['zs_type_fl'], 'zs_qj': 'zs_qj_ck', 'zs_wzgx': 'zs_wzgx_gd', 'zs_optimize': '0', 'idx_macd_fast': '12', 'idx_macd_slow': '26', 'idx_macd_signal': '9', 'fx_qy': 'fx_qy_middle', 'xd_zs_max_lines_split': '11', 'allow_split_one_line_to_xd': '0', 'allow_bi_fx_strict': '1', 'enable_kchart_low_to_high': '0', 'bi_split_k_cross_nums': '99,0', 'fx_check_k_nums': '99', 'cl_mmd_cal_qs_1mmd': '1', 'cl_mmd_cal_not_qs_3mmd_1mmd': '1', 'cl_mmd_cal_qs_3mmd_1mmd': '1', 'cl_mmd_cal_qs_not_lh_2mmd': '1', 'cl_mmd_cal_qs_bc_2mmd': '1', 'cl_mmd_cal_3mmd_not_lh_bc_2mmd': '1', 'cl_mmd_cal_1mmd_not_lh_2mmd': '1', 'cl_mmd_cal_3mmd_xgxd_not_bc_2mmd': '1', 'cl_mmd_cal_not_in_zs_3mmd': '1', 'cl_mmd_cal_not_in_zs_gt_9_3mmd': '1', 'chart_show_infos': '1', 'chart_show_fx': '1', 'chart_show_bi': '1', 'chart_show_xd': '1', 'chart_show_zsd': '1', 'chart_show_qsd': '1', 'chart_show_bi_zs': '1', 'chart_show_xd_zs': '1', 'chart_show_zsd_zs': '1', 'chart_show_qsd_zs': '1', 'chart_show_bi_mmd': '1', 'chart_show_xd_mmd': '1', 'chart_show_zsd_mmd': '1', 'chart_show_qsd_mmd': '1', 'chart_show_bi_bc': '1', 'chart_show_xd_bc': '1', 'chart_show_zsd_bc': '1', 'chart_show_qsd_bc': '1', 'chart_show_ma': '1', 'chart_show_boll': '1', 'chart_show_futu': 'macd', 'chart_show_atr_stop_loss': False, 'chart_show_ld': 'xd', 'chart_kline_nums': 1000, 'chart_idx_ma_period': '120,250', 'chart_idx_vol_ma_period': '5,60', 'chart_idx_boll_period': 20, 'chart_idx_rsi_period': 14, 'chart_idx_atr_period': 14, 'chart_idx_atr_multiplier': 1.5, 'chart_idx_cci_period': 14, 'chart_idx_kdj_period': '9,3,3', 'chart_qstd': 'xd,0', 'judge_zs_qs_level': '1', 'xd_allow_bi_pohuai': 'yes_qk', 'xd_allow_split_no_highlow': '1', 'xd_allow_split_zs_kz': '0', 'xd_allow_split_zs_more_line': '1', 'xd_allow_split_zs_no_direction': '0'}
交易总手续费 : 151117.15658219086

首个交易日：2019-01-02 00:00:00+08:00 最后交易日：2024-12-31 00:00:00+08:00 总交易日：1456
起始资金：1,000,000.00 结束资金：2,108,961.06 总手续费：151,117.16
基准收益率：34.18%  基准年化收益：5.63%%
总收益率：110.90% 年化收益率：18.28%
最大回撤：-555,203.86 百分比最大回撤：-27.15% 最长回撤天数：308
日均收益率：0.05% 收益标准差：1.22% Sharpe Ratio: 0.63 收益回撤比：4.08
+--------------+------+------+--------+-----------+------------+------------+----------+----------+----------+--------+
|    买卖点    | 成功 | 失败 |  胜率  |    盈利   |    亏损    |   净利润   | 回吐比例 | 平均盈利 | 平均亏损 | 盈亏比 |
+--------------+------+------+--------+-----------+------------+------------+----------+----------+----------+--------+
|   一类买点   |  46  | 153  | 23.12% | 3074767.1 | 1966516.54 | 1108250.56 |  63.96   | 66842.76 | 12853.05 | 5.2005 |
|   二类买点   |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  类二类买点  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|   三类买点   |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  类三类买点  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  下跌笔背驰  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 下跌线段背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 下跌盘整背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 下跌趋势背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|   一类卖点   |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|   二类卖点   |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  类二类卖点  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|   三类卖点   |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  类三类卖点  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|  上涨笔背驰  |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 上涨线段背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 上涨盘整背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
| 上涨趋势背驰 |  0   |  0   |   0%   |     0     |     0      |     0      |    0     |    0     |    0     |   0    |
|     汇总     |  46  | 153  | 23.12% | 3074767.1 | 1966516.54 | 1108250.56 |  63.96   | 66842.76 | 12853.05 | 5.2005 |
+--------------+------+------+--------+-----------+------------+------------+----------+----------+----------+--------+

In [20]:
a= [-1,-2, 0, 2]
print(sorted(a,reverse=False))
# (a.sort(reverse=False))

[-2, -1, 0, 2]

In [15]:
# 保存一个修改持仓附加信息的策略文件
BT.save_file = save_bt_path + '_add_pos.pkl'
BT.strategy = None
for _code, _poss in BT.trader.positions_history.items():
    for _p in _poss:
        print(_p.loss_price)
        print(_p.price)
        _p.info["loss_rate"] = (_p.price - _p.loss_price) / _p.price * 100
        print(_p.info["loss_rate"])
# print(BT.trader.balance_history)
# print(BT.trader.hold_profit_history)
# print(BT.trader.positions_balance_history)
print(BT.orders)
BT.save()

save to : D:/xuangu_log/backtrade/a_strategy_Dnbbc_20250107_add_pos.pkl

1.97
2.12
7.075471698113213
86.27
89.43
3.533489880353361
3.35
3.52
4.829545454545452
7.680000000000001
9.01
14.761376248612642
8.21
8.6
4.534883720930219
6.930000000000001
7.39
6.22462787550743
6.96
7.4
5.945945945945951
6.15
6.34
2.9968454258675
7.9
8.12
2.7093596059113163
7.640000000000001
7.89
3.1685678073510664
9.99
10.38
3.7572254335260165
28.66
30.29
5.381313965004949
27.56
28.39
2.9235646354350187
24.919999999999998
26.63
6.421329327825765
11.4
11.74
2.896081771720612
11.39
11.5
0.9565217391304299
10.790000000000001
11.0
1.9090909090909005
10.42
10.63
1.975540921919105
7.2700000000000005
7.49
2.9372496662216254
11.23
12.2
7.950819672131139
27.15
28.96
6.250000000000008
19.4
20.87
7.043603258265464
19.04
20.08
5.179282868525893
18.099999999999998
18.63
2.8448738593666194
17.419999999999998
18.43
5.480195333695071
9.08
11.32
19.787985865724384
34.64
35.56
2.587176602924639
11.9
12.19
2.3789991796554486
11.86
12.38
4.20032310177707
1.75
1.88
6.914893617021272
9.31
9.54
2.4109014675052274
14.9
15.36
2.9947916666666607
5.8500000000000005
5.95
1.680672268907557
5.720000000000001
6.07
5.766062602965397
5.21
5.29
1.5122873345935741
63.61
64.42
1.257373486494881
62.190000000000005
63.09
1.4265335235378007
61.79
63.34
2.4471108304389078
60.02
61.57
2.517459801851546
15.11
16.25
7.015384615384619
15.76
16.15
2.414860681114544
15.71
16.11
2.4829298572315244
15.200000000000001
15.39
1.2345679012345647
14.89
15.24
2.2965879265091838
14.68
15.17
3.230059327620305
14.120000000000001
14.51
2.687801516195719
225.95000000000002
229.91
1.7224131181766689
210.0
213.39
1.5886405173625693
3.37
3.47
2.8818443804034604
3.3800000000000003
3.43
1.4577259475218607
3.3200000000000003
3.41
2.63929618768328
12.3
12.64
2.689873417721518
8.93
9.26
3.563714902807776
13.8
14.34
3.7656903765690317
13.66
13.73
0.5098324836125293
12.700000000000001
12.91
1.6266460108442995
12.38
12.77
3.0540328895849553
5.82
5.95
2.18487394957983
17.99
18.32
1.8013100436681324
17.259999999999998
17.78
2.9246344206974304
16.83
17.59
4.320636725412175
3.56
3.78
5.820105820105813
12.07
12.48
3.285256410256411
9.97
10.33
3.4849951597289395
7.78
8.04
3.233830845771131
9.15
9.37
2.347918890074695
12.81
13.59
5.7395143487858675
5.83
6.02
3.1561461794019854
9.3
9.79
5.005107252298248
14.34
15.56
7.84061696658098
13.89
14.52
4.338842975206605
4.8100000000000005
5.06
4.940711462450576
4.6000000000000005
5.02
8.366533864541815
4.430000000000001
4.65
4.731182795698919
18.54
19.57
5.263157894736848
18.259999999999998
19.79
7.731177362304201
17.99
18.44
2.4403470715835294
17.29
18.31
5.570726379027851
15.26
15.67
2.6164645820038297
15.07
15.75
4.3174603174603154
23.79
24.55
3.095723014256625
22.939999999999998
23.3
1.5450643776824162
4.59
4.75
3.3684210526315814
4.970000000000001
5.17
3.868471953578323
4.680000000000001
4.91
4.684317718940927
30.259999999999998
30.63
1.2079660463597814
30.13
31.15
3.2744783306581047
29.15
31.94
8.735128365685668
78.89999999999999
82.95
4.882459312839074
1.84
1.92
4.166666666666659
1.83
1.95
6.153846153846148
17.66
18.12
2.538631346578371
2.85
2.94
3.0612244897959133
2.81
2.88
2.43055555555555
2.8000000000000003
2.87
2.4390243902438966
2.6500000000000004
2.73
2.930402930402917
2.39
2.47
3.2388663967611366
22.15
23.0
3.69565217391305
20.68
21.26
2.728127939793047
25.139999999999997
27.25
7.743119266055057
4.11
4.2
2.1428571428571392
4.0200000000000005
4.18
3.8277511961722315
8.74
9.48
7.8059071729957825
5.67
5.82
2.577319587628872
171.16
178.11
3.9020829824265997
3.8400000000000003
4.07
5.65110565110565
5.2700000000000005
5.42
2.7675276752767433
4.94
5.16
4.263565891472863
4.26
4.46
4.48430493273543
4.180000000000001
4.31
3.0162412993039216
4.12
4.2
1.9047619047619064
2.5300000000000002
2.63
3.8022813688212795
2.54
2.6
2.3076923076923097
2.52
2.61
3.44827586206896
2.49
2.59
3.861003861003848
12.02
12.58
4.451510333863279
11.02
11.47
3.923278116826513
4.34
4.58
5.240174672489087
9.46
9.64
1.867219917012445
9.13
9.3
1.8279569892473109
3.9600000000000004
4.06
2.463054187192099
6.96
7.43
6.325706594885595
10.25
10.89
5.876951331496791
9.14
9.59
4.692387904066729
9.0
9.36
3.84615384615384
7.46
8.18
8.801955990220046
292.77
300.84
2.682489030713999
13.47
13.6
0.9558823529411693
13.46
14.4
6.527777777777774
2.2100000000000004
2.33
5.150214592274663
16.47
17.28
4.687500000000013
7.45
8.45
11.83431952662721
17.16
17.57
2.3335230506545255
2.58
2.75
6.181818181818179
3.7100000000000004
3.93
5.5979643765903235
4.8
5.08
5.511811023622052
9.82
10.66
7.879924953095683
7.04
7.2
2.222222222222224
6.88
7.11
3.2348804500703294
10.26
10.68
3.9325842696629207
11.63
12.49
6.885508406725376
11.53
12.33
6.488240064882407
10.41
11.03
5.6210335448776
9.52
9.92
4.032258064516133
8.44
8.58
1.6317016317016382
8.3
8.45
1.7751479289940661
7.45
7.82
4.73145780051151
7.42
7.85
5.477707006369424
7.04
7.2
2.222222222222224
3.0
3.17
5.362776025236591
6.94
7.13
2.664796633941087
6.69
6.78
1.327433628318582
6.53
6.69
2.3916292974588957
15.82
16.09
1.6780609073958956
14.02
14.4
2.638888888888894
13.870000000000001
14.43
3.8808038808038723
8.22
8.97
8.361204013377927
77.19999999999999
81.25
4.984615384615399
7.55
7.76
2.706185567010309
6.3500000000000005
6.54
2.905198776758402
3.25
3.43
5.247813411078721
3.1300000000000003
3.21
2.492211838006219
2.9200000000000004
3.05
4.262295081967196
1.64
1.71
4.093567251461992
76.41
76.82
0.5337151783389699
74.94
80.07
6.406893967778189
24.41
24.97
2.2426912294753656
23.61
24.44
3.3960720130932973
23.33
24.34
4.149548069022193
2.6700000000000004
2.78
3.95683453237408
14.44
15.02
3.8615179760319576
13.89
14.36
3.27298050139275
15.02
15.52
3.221649484536083
14.83
15.14
2.0475561426684314
14.58
15.15
3.7623762376237644
4.49
4.7
4.468085106382977
4.17
4.54
8.149779735682822
9.8
10.22
4.109589041095889
6.2700000000000005
7.15
12.307692307692305
7.220000000000001
7.44
2.9569892473118244
18.04
18.38
1.849836779107725
17.689999999999998
18.47
4.223064428803471
9.5
9.84
3.455284552845527
11.77
12.15
3.127572016460912
4.65
4.75
2.1052631578947296
6.32
6.7
5.671641791044775
7.08
7.3
3.013698630136983
13.49
13.75
1.8909090909090893
15.57
16.2
3.8888888888888826
12.77
14.07
9.239516702203273
5.76
5.99
3.8397328881469184
51.78
53.76
3.6830357142857086
51.13
53.21
3.909039654200335
2.9600000000000004
3.05
2.9508196721311286
2.95
3.07
3.908794788273605
4.03
4.25
5.176470588235288
8.63
9.16
5.786026200873355
1.53
1.57
2.5477707006369448
1.52
1.62
6.172839506172845
7.640000000000001
8.42
9.263657957244648
7.46
7.66
2.6109660574412556
6.890000000000001
7.06
2.4079320113314315
5.75
6.18
6.957928802588992
11.0
11.51
4.430929626411814
14.31
14.66
2.3874488403819893
14.27
14.72
3.0570652173913113
14.200000000000001
14.58
2.6063100137174144
5.29
5.42
2.3985239852398506
8.59
8.78
2.1640091116173066
8.01
8.39
4.529201430274145
9.82
10.09
2.6759167492566855
13.27
14.44
8.102493074792244
22.38
23.44
4.522184300341307
26.669999999999998
28.67
6.9759330310429135
5.67
5.94
4.545454545454553
4.970000000000001
5.3
6.2264150943396075
15.46
16.69
7.3696824445775935
4.99
5.08
1.771653543307084
4.78
4.92
2.8455284552845463
7.3
7.62
4.199475065616801
8.47
8.76
3.310502283105013
4.91
5.03
2.385685884691851
82.72
84.8
2.4528301886792434
82.11
85.05
3.4567901234567877
79.42
81.85
2.96884544899205
83.58
84.66
1.2756909992912808
80.88
84.54
4.3293115684883015
83.14
83.58
0.5264417324718805
7.17
7.68
6.640624999999997
6.5600000000000005
7.01
6.419400855920104
13.76
14.31
3.843466107617056
13.26
14.42
8.044382801664355
14.75
15.11
2.382528127068163
4.180000000000001
4.37
4.347826086956511
3.5500000000000003
3.63
2.2038567493112846
50.17
51.3
2.202729044834299
71.17999999999999
73.35
2.9584185412406296
69.38
70.75
1.9363957597173207
4.01
4.11
2.433090024330913
3.85
4.01
3.9900249376558534
12.05
12.31
2.1121039805036537
10.870000000000001
11.67
6.855184233076255
7.11
7.54
5.7029177718832855
6.24
6.7
6.865671641791043
5.7700000000000005
6.15
6.178861788617884
8.67
9.59
9.593326381647548
10.75
11.3
4.867256637168148
30.65
31.82
3.676932746700194
30.22
31.36
3.635204081632655
17.68
20.25
12.69135802469136
17.189999999999998
17.53
1.9395322304620841
16.7
17.19
2.850494473531134
53.690000000000005
55.7
3.6086175942549334
4.640000000000001
4.79
3.1315240083507194
34.800000000000004
38.55
9.72762645914395
34.09
36.86
7.514921323928367
12.040000000000001
12.45
3.2931726907630394
12.01
12.14
1.0708401976935813
11.19
11.52
2.864583333333334
16.459999999999997
17.09
3.6863662960795933
16.369999999999997
16.91
3.1933767001774256
4.75
4.88
2.663934426229506
2.0700000000000003
2.2
5.909090909090904
11.69
12.22
4.337152209492644
10.08
10.32
2.325581395348839
9.68
10.43
7.1907957813998085
35.14
39.2
10.357142857142861
31.169999999999998
31.85
2.135007849293574
2.8000000000000003
2.96
5.4054054054053955
3.1700000000000004
3.3
3.939393939393923
2.85
2.99
4.682274247491643
15.290000000000001
15.75
2.9206349206349147
14.83
15.32
3.1984334203655367
9.46
9.74
2.8747433264886997
12.06
12.41
2.8203062046736473
11.94
12.14
1.647446457990124
7.66
8.27
7.376058041112449
9.38
9.93
5.53877139979858
9.56
9.81
2.54841997961264
9.49
9.99
5.005005005005005
17.52
18.41
4.834329168929933
50.410000000000004
52.5
3.980952380952374
7.5
7.8
3.8461538461538445
7.3
7.8
6.4102564102564115
16.41
16.95
3.185840707964597
16.11
16.56
2.7173913043478217
13.89
14.67
5.31697341513292
3.2600000000000002
3.46
5.780346820809241
2.58
3.01
14.285714285714276
65.5
67.81
3.406577201002805
64.80999999999999
71.73
9.647288442771526
10.02
10.61
5.560791705937794
9.9
10.21
3.036238981390798
9.46
10.0
5.3999999999999915
6.19
6.35
2.519685039370067
5.7700000000000005
5.93
2.6981450252950974
4.3100000000000005
4.42
2.488687782805417
4.1000000000000005
4.21
2.612826603325402
6.37
6.77
5.908419497784336
13.86
14.34
3.347280334728037
13.51
13.65
1.0256410256410298
12.620000000000001
13.11
3.7376048817696295
4.91
5.29
7.183364839319468
16.18
16.81
3.7477691850089174
16.04
16.26
1.3530135301353161
15.11
15.8
4.367088607594945
6.42
6.77
5.169867060561295
2.4800000000000004
2.96
16.2162162162162
4.32
4.42
2.262443438914019
11.01
11.4
3.4210526315789522
10.85
11.14
2.6032315978456095
13.67
14.21
3.8001407459535597
5.71
6.52
12.423312883435578
4.180000000000001
4.26
1.8779342723004504
15.13
15.51
2.4500322372662735
15.040000000000001
15.52
3.0927835051546304
13.78
13.85
0.5054151624548757
13.49
13.81
2.3171614771904436
12.86
13.16
2.279635258358668
11.94
12.4
3.709677419354845
10.78
11.29
4.517271922054914
6.91
7.24
4.558011049723758
6.470000000000001
6.75
4.148148148148139
36.57
37.26
1.8518518518518459
34.160000000000004
36.37
6.076436623590855
13.120000000000001
13.53
3.0303030303030183
13.1
13.44
2.5297619047619038
12.91
13.25
2.5660377358490556
5.33
5.55
3.9639639639639594
30.83
33.12
6.914251207729466
30.31
33.32
9.033613445378155
6.970000000000001
7.09
1.692524682651611
6.45
6.6
2.272727272727265
11.96
12.12
1.3201320132013068
6.41
6.67
3.8980509745127407
2.04
2.16
5.55555555555556
1.79
1.94
7.7319587628865944
4.890000000000001
5.15
5.048543689320384
21.049999999999997
23.97
12.181894034209437
20.2
20.66
2.2265246853823855
5.6000000000000005
5.89
4.923599320882839
5.220000000000001
5.83
10.46312178387649
22.209999999999997
23.13
3.977518374405541
10.24
10.72
4.4776119402985115
115.94
121.68
4.7172912557528015
106.36999999999999
109.23
2.6183282980866185
104.69
108.48
3.493731563421835
100.64
111.71
9.9095873243219
98.61999999999999
100.51
1.8804099094617597
96.27
102.15
5.756240822320127
49.940000000000005
53.35
6.391752577319582
47.690000000000005
51.3
7.037037037037022
6.96
7.22
3.601108033240994
4.63
4.8
3.541666666666665
5.11
5.3
3.5849056603773493
3.47
3.58
3.0726256983240186
3.3800000000000003
3.49
3.1518624641833775
7.140000000000001
7.26
1.6528925619834605
3.8000000000000003
3.94
3.553299492385779
18.45
19.23
4.0561622464898655
10.49
10.74
2.3277467411545625
10.06
10.66
5.628517823639771
20.169999999999998
20.81
3.075444497837581
14.84
14.95
0.7357859531772538
14.620000000000001
15.1
3.1788079470198585
18.54
18.81
1.435406698564591
22.259999999999998
23.03
3.3434650455927186
6.75
7.01
3.708987161198285
6.430000000000001
6.61
2.7231467473524917
6.41
6.66
3.7537537537537538
9.07
9.47
4.223864836325241
8.78
8.93
1.679731243001124
8.77
8.91
1.571268237934911
8.040000000000001
8.32
3.3653846153846074
7.96
8.3
4.096385542168683
52.7
54.23
2.8213166144200517
45.77
48.3
5.238095238095226
44.24
45.49
2.747856671795999
23.81
24.92
4.454253611556994
22.279999999999998
23.1
3.549783549783566
12.72
13.56
6.194690265486724
4.21
4.32
2.5462962962963034
4.03
4.13
2.4213075060532603
3.4400000000000004
3.61
4.709141274238212
8.03
8.1
0.8641975308642011
7.65
7.89
3.041825095057026
18.729999999999997
19.14
2.142110762800437
18.27
19.74
7.446808510638293
6.67
7.23
7.745504840940532
4.3500000000000005
4.53
3.9735099337748276
3.18
3.34
4.790419161676638
1.54
1.67
7.784431137724544
22.66
23.34
2.913453299057411
4.26
4.44
4.054054054054068
35.74
36.68
2.5627044711014113
9.69
9.97
2.8084252758274935
9.66
10.03
3.688933200398796
3.0100000000000002
3.1
2.903225806451608
2.99
3.19
6.269592476489019
4.04
4.24
4.7169811320754755
9.49
9.75
2.6666666666666643
9.32
9.71
4.016477857878481
9.290000000000001
9.5
2.2105263157894637
8.66
8.83
1.925254813137032
8.57
8.78
2.3917995444191242
8.48
8.97
5.462653288740247
1.7
1.86
8.602150537634417
6.79
7.22
5.955678670360108
8.18
8.54
4.215456674473062
9.4
10.32
8.914728682170542
9.32
9.57
2.612330198537095
7.8500000000000005
8.31
5.535499398315282
4.970000000000001
5.02
0.9960159362549589
26.06
26.87
3.014514328247124
25.47
26.32
3.229483282674778
25.299999999999997
26.04
2.8417818740399463
22.919999999999998
23.81
3.737925241495173
18.75
19.41
3.40030911901082
11.290000000000001
11.69
3.4217279726261642
11.86
13.33
11.027756939234813
12.75
13.26
3.8461538461538445
4.9
5.0
1.9999999999999927
4.73
4.81
1.6632016632016462
39.92
41.66
4.176668266922696
3.64
3.77
3.4482758620689626
40.03
41.09
2.57970309077635
45.6
48.36
5.7071960297766715
45.53
46.51
2.1070737475811585
41.46
43.39
4.448029499884766
3.95
4.18
5.502392344497597
3.12
3.2
2.500000000000002
2.95
3.07
3.908794788273605
3.4800000000000004
3.72
6.451612903225799
28.209999999999997
28.5
1.0175438596491324
27.849999999999998
30.33
8.176722716782066
48.35
51.62
6.334753971328936
38.24
39.87
4.088286932530714
38.17
39.28
2.8258655804480637
37.47
38.26
2.064819654992157
1.82
2.04
10.784313725490195
3.4200000000000004
3.71
7.816711590296485
3.2600000000000002
3.47
6.051873198847261
6.42
6.77
5.169867060561295
48.52
49.26
1.5022330491270706
19.759999999999998
21.47
7.964601769911509
5.38
5.57
3.411131059245967
4.44
4.56
2.6315789473684044
4.390000000000001
4.54
3.3039647577092395
16.09
16.64
3.3052884615384657
16.02
16.45
2.6139817629179314
15.51
15.71
1.273074474856786
15.05
15.46
2.652005174644244
44.06
45.6
3.377192982456138
6.94
7.15
2.937062937062936
6.57
6.76
2.8106508875739573
3.4400000000000004
3.62
4.972375690607727
4.09
4.23
3.3096926713948123
12.77
13.26
3.695324283559579
12.75
12.95
1.544401544401539
12.05
12.36
2.5080906148867212
4.4
4.48
1.785714285714287
10.05
10.57
4.9195837275307435
7.140000000000001
7.4
3.51351351351351
7.140000000000001
7.29
2.0576131687242727
7.13
7.29
2.194787379972567
6.98
7.13
2.1037868162692774
8.290000000000001
8.44
1.7772511848341066
29.389999999999997
30.89
4.855940433797357
9.53
9.98
4.509018036072155
11.42
12.37
7.679870654810019
8.86
9.77
9.314227226202663
13.41
13.83
3.0368763557483724
13.28
13.71
3.1363967906637598
12.99
13.36
2.769461077844306
12.97
13.36
2.9191616766466977
8.03
8.25
2.6666666666666745
7.6000000000000005
7.76
2.0618556701030832
9.950000000000001
10.3
3.3980582524271807
9.5
9.83
3.3570701932858604
9.28
9.59
3.232533889468201
27.68
28.32
2.25988700564972
27.45
28.24
2.7974504249291754
3.2100000000000004
3.33
3.603603603603593
3.18
3.26
2.453987730061338
2.89
3.04
4.934210526315787
15.9
16.96
6.250000000000003
11.01
11.39
3.336259877085169
16.709999999999997
17.73
5.752961082910339
15.950000000000001
16.65
4.20420420420419
14.86
15.36
3.2552083333333335
14.08
14.38
2.086230876216973
21.4
21.93
2.416780665754679
11.98
12.82
6.552262090483618
2.7300000000000004
2.86
4.545454545454526
13.83
15.79
12.412919569347682
24.86
25.46
2.3566378633150094
24.54
25.94
5.397070161912112
26.279999999999998
26.81
1.976874300634096
23.54
25.0
5.840000000000003
9.43
9.74
3.1827515400410724
9.52
9.84
3.2520325203252063
8.950000000000001
9.24
3.1385281385281294
8.81
9.25
4.756756756756751
7.220000000000001
7.75
6.838709677419347
7.180000000000001
7.8
7.948717948717938
7.4
7.7
3.896103896103894
10.01
10.18
1.6699410609037322
9.68
9.97
2.9087261785356158
16.29
16.44
0.9124087591241006
15.98
16.42
2.6796589524969625
6.49
6.99
7.153075822603719
20.759999999999998
21.68
4.243542435424362
297.0
303.2
2.044854881266487
294.79
300.69
1.9621537131264681
283.79
290.0
2.1413793103448207
278.12
300.2
7.355096602265151
9.09
9.42
3.5031847133757967
8.83
9.02
2.1064301552106377
8.33
8.58
2.9137529137529135
10.91
11.22
2.7629233511586495
14.67
15.45
5.048543689320384
10.49
10.81
2.9602220166512514
4.49
4.84
7.231404958677679
3.83
4.1
6.585365853658527
9.48
9.98
5.0100200400801596
16.95
17.65
3.966005665722376
5.03
5.31
5.273069679849329
9.700000000000001
9.99
2.9029029029028943
6.04
6.33
4.58135860979463
7.640000000000001
7.98
4.2606516290726795
8.05
8.3
3.012048192771084
13.18
14.37
8.281141266527484
15.700000000000001
16.18
2.9666254635352205
15.44
16.13
4.277743335399873
13.85
14.08
1.6335227272727304
3.9000000000000004
4.07
4.176904176904174
4.54
4.69
3.1982942430703694
17.779999999999998
18.37
3.2117583015786795
17.18
18.24
5.811403508771924
8.77
8.94
1.9015659955257262
8.16
8.27
1.3301088270858457
7.970000000000001
8.62
7.540603248259845
13.51
13.82
2.2431259044862553
16.52
17.1
3.3918128654970867
2.99
3.11
3.8585209003215324
2.95
3.02
2.3178807947019817
7.21
7.6
5.131578947368417
11.19
11.49
2.610966057441259
4.680000000000001
5.1
8.23529411764704
24.9
26.41
5.717531238167367
22.049999999999997
25.04
11.940894568690103
5.1000000000000005
5.16
1.162790697674411
18.22
19.29
5.546915500259204
16.619999999999997
18.36
9.477124183006547
21.299999999999997
23.33
8.701243034719251
4.92
5.28
6.818181818181824
8.540000000000001
9.11
6.2568605927551975
15.290000000000001
15.5
1.3548387096774135
15.55
17.28
10.011574074074076
18.79
19.42
3.2440782698249357
19.569999999999997
25.33
22.73983418870905
152.68
155.16
1.598350090229434
152.54000000000002
163.28
6.577658010779018
23.069999999999997
23.58
2.1628498727735437
21.889999999999997
22.43
2.4074899687918085
16.91
17.36
2.5921658986175076
16.88
17.43
3.155479059093521
6.99
7.15
2.2377622377622397
6.58
6.91
4.7756874095513755
6.49
6.72
3.4226190476190412
39.510000000000005
42.51
7.057163020465756
5.390000000000001
5.65
4.60176991150442
4.29
4.51
4.878048780487799
6.13
6.51
5.837173579109062
9.78
10.69
8.512628624883071
16.15
16.57
2.534701267350644
15.53
15.84
1.9570707070707103
14.58
14.86
1.8842530282637913
17.189999999999998
17.5
1.7714285714285845
6.49
6.71
3.27868852459016
6.09
6.29
3.1796502384737706
4.09
4.25
3.7647058823529442
3.4400000000000004
3.54
2.824858757062137
13.700000000000001
14.34
4.463040446304036
10.07
10.29
2.1379980563653924
10.03
10.17
1.3765978367748335
9.97
10.18
2.062868369351661
16.939999999999998
17.37
2.475532527346018
3.74
3.94
5.076142131979688
14.52
14.92
2.680965147453086
17.41
18.16
4.129955947136564
5.140000000000001
5.48
6.204379562043792
2.54
2.63
3.422053231939158
6.37
6.84
6.871345029239763
5.5200000000000005
6.06
8.910891089108897
7.4
7.83
5.491698595146867
6.3500000000000005
6.82
6.891495601173017
26.2
30.15
13.101160862354892
27.84
29.16
4.526748971193417
2.95
3.06
3.594771241830061
28.47
29.38
3.0973451327433636
12.61
13.21
4.542013626040889
11.77
12.23
3.761242845461986
16.59
16.96
2.1816037735849116
15.47
16.08
3.7935323383084434
14.98
15.13
0.9914077990746885
14.51
15.0
3.2666666666666684
14.4
15.04
4.255319148936162
16.22
17.05
4.8680351906158466
19.529999999999998

In [4]:
# 保存一个不包含策略对象与持仓附加信息的策略文件
BT.save_file = save_bt_path + '_no_strategy.pkl'
BT.strategy = None
for _code, _poss in BT.trader.positions_history.items():
    for _p in _poss:
        _p.info = {}
BT.trader.balance_history = {}
BT.trader.hold_profit_history = {}
BT.trader.positions_balance_history = {}
BT.orders = {}
BT.save()

save to : D:/xuangu_log/backtrade/a_strategy_Dnbbc_20250107_no_strategy.pkl

In [22]:
# 回测数据展示
BT.backtest_charts()

In [23]:
# 显示历史持仓
# 设置显示全部行，不省略
pd.set_option("display.max_rows", None)
# 设置显示全部列，不省略
pd.set_option("display.max_columns", None)

# 读取策略中包含的附加信息与平仓uid信息
info_keys = []
close_uids = []
for _, _poss in BT.trader.positions_history.items():
    for _p in _poss:
        # print(_p.info)
        info_keys += list(_p.info.keys())
        close_uids += list([_or["close_uid"] for _or in _p.close_records])
info_keys = list(sorted(list(set(info_keys))))
close_uids = list(sorted(list(set(close_uids))))
print(info_keys)
print(close_uids)

# 显示指定标的的持仓

pos_df = BT.positions(add_columns=info_keys, close_uids=['clear'])
pos_df['_win'] = pos_df['profit_rate'].apply(lambda p: int(p>0))
pos_df.groupby(['mmd']).agg({'profit_rate': {'mean', 'sum', 'count'}, '_win': {'mean', 'sum', 'count'}})

['__open_k_date', 'k_delta', 'loss_rate', 'macd_bi_last_most_in_macd_bi', 'opt_mmd', 'xd4_xcld']
['clear']

     profit_rate                   _win
           count      mean    sum count      mean sum
mmd
1buy         199  2.288442  455.4   199  0.231156  46

In [24]:
# 显示历史持仓
#设置显示全部行，不省略
pd.set_option('display.max_rows',None)
#设置显示全部列，不省略
pd.set_option('display.max_columns',None)

# 读取策略中包含的附加信息与平仓uid信息
info_keys = []
close_uids = []
for _, _poss in BT.trader.positions_history.items():
    for _p in _poss:
        # print(_p.info)
        info_keys += list(_p.info.keys())
        close_uids += list(_p.close_uid_profit.keys())
info_keys = list(sorted(list(set(info_keys))))
close_uids = list(sorted(list(set(close_uids))))
print(info_keys)
print(close_uids)

# 显示指定标的的持仓

pos_df = BT.positions(add_columns=info_keys, close_uids=['clear'])
pos_df['_win'] = pos_df['profit_rate'].apply(lambda p: int(p>0))
pos_df.groupby(['mmd']).agg({'profit_rate': {'mean', 'sum', 'count'}, '_win': {'mean', 'sum', 'count'}})

['__open_k_date', 'k_delta', 'loss_rate', 'macd_bi_last_most_in_macd_bi', 'opt_mmd', 'xd4_xcld']
['clear']

     profit_rate                   _win
           count      mean    sum count      mean sum
mmd
1buy         199  2.288442  455.4   199  0.231156  46

In [25]:
print(len(pos_df))
# 过滤条件
pos_querys = [
    " k_delta <= 3",
    # " xd4_xcld <= 0.2",
    # " xd4_xcld <= 0.5"
]
for _q in pos_querys:
    pos_df = pos_df.query(_q)
print(len(pos_df))

199

UndefinedVariableError: name 'k_delda' is not defined

In [ ]:
pos_df = BT.positions(add_columns=info_keys, close_uids=['clear'])
pos_df['_win'] = pos_df['profit_rate'].apply(lambda p: int(p>0))
pos_df.groupby(['mmd']).agg({'profit_rate': {'mean', 'sum', 'count'}, '_win': {'mean', 'sum', 'count'}})

In [ ]:
fun = lambda x: int(x >= 2)
x_key = 'xd4_xcld'
groupbys = ['opt_mmd',]
pos_df['_x'] = pos_df[x_key].apply(fun)
pos_df.groupby(groupbys).agg({'profit_rate': {'mean', 'sum', 'count'}, '_win': {'count', 'sum', 'mean'}})

In [ ]:
# fun = lambda x: (x >= 2)
# x_key = 'xd4_xcld'
# pos_df['_x'] = pos_df[x_key].apply(fun)
groupbys = ['opt_mmd',]
print(len(pos_df))
pos_df.groupby(groupbys).agg({'profit_rate': {'mean', 'sum', 'count'}, '_win': {'count', 'sum', 'mean'}})

In [ ]:
# 显示标的周期的图标
BT.show_charts(BT.codes[0], BT.frequencys[0])